### ISSUE TITLE
Suggestion : add somewhere that other browsers need to be closed before importing

### ISSUE THREAD

**Issue by nado** [JustOff/password-backup-tool#1]
Hi,

I felt very dumb when this happened to me. I tried importing chrome passwords while having it still opened at the same time.
I received an error saying that the extension couldnt import chrome passwords and couldnt understand why.

It is only after a few minutes that I thought about closing chrome before trying again, it seems really logical to do that, but I still managed to forget about it, maybe adding a note about it in the web page ( https://addons.palemoon.org/addon/password-backup-tool/ ) or in the error message could be useful to some people ?

**Comment by JustOff** [comment]
Thank you for the suggestion. I've added this note to the add-on description.

**Comment by LL25255252** [comment]
Please add it also to the description here in the github page.

**Comment by JustOff** [comment]
[Done](https://github.com/JustOff/password-backup-tool/commit/3fb9c15d82c1f8b45a1476fb6a125cfdc67ec043).
