### ISSUE TITLE
PBT can't import from Chrome .csv

### ISSUE THREAD

**Issue by dzenifr** [JustOff/password-backup-tool#2]
1. Open Chrome > Settings > Advanced > Manage Passwords
2. Click ... > Export Passwords > Click Export Passwords... > (Enter Windows PW)
3. Save CSV file
4. Open Pale Moon > about:addons > Password Backup Tool > Options > Import Passwords
5. Navigate to Chrome Passwords.csv > Select File > Click Open
6. Error Message
[JavaScript Application]
Cannot import from this file.

**Comment by JustOff** [comment]
The correct sequence is as follows:
1) Password Backup Tool > Options > Import Passwords
2) Paste `"%LOCALAPPDATA%\Google\Chrome\User Data\Default\Login Data"` into the "File name" field
3) Click "Open"

**Comment by dzenifr** [comment]
Error Message:
[JavaScript Application]
Error: Couldn't get rows from Chrome passwords database.

[edit]  1. Close Chrome again if you opened it.
smdh.

Thank you! It worked.

**Comment by JustOff** [comment]
You are welcome.
