### ISSUE TITLE
Waterfox Add-ons Manager didn't find the last release

### ISSUE THREAD

**Issue by LL25255252** [JustOff/password-backup-tool#3]
Add-ons Manager > Password-backup-tool 1.1.0 > find updates for 
No results

Win 7 x64
Waterfox 56.2.7.1 (64-bit)

Thanks in advance.

Meanwhile I'll use RSS for notifications on new releases - https://github.com/JustOff/password-backup-tool/releases.atom

**Comment by JustOff** [comment]
Well, this is expected as PBT does not provide self-hosted updates and Waterfox by default relies on AMO only. It would be much easier if it had its own add-on site, and I hope this will happen someday, but until then I can't promise anything specific, sorry.
