### ISSUE TITLE
Almost duplicate entries. This login already exists.

### ISSUE THREAD

**Issue by dapgo** [JustOff/password-backup-tool#4]
This failure is common to password exporter.
http://ftp.xxxx.yyy.zzz:22 ([JavaScript Error: "This login already exists.

The exporter displays that 153 entries have been exported
The import displays that 140 entries are going to be imported

Looking in source browser for ftp.xxxx.yyy.zzz I can see the following entries:
http://ftp.xxxx.yyy.zzz:22  anonymous
ftp.xxxx.yyy.zzz:22  anonymous

I don't know if above type of duplicates can be related to the use of FireFTP .

**Comment by dapgo** [comment]
after removing ftp duplicates I have found another error with a bookmark called "chrome://isreaditlater"

chrome://isreaditlater ([JavaScript Error: "This login already exists." {file: "resource://gre/components/nsLoginManager.js" line: 308}]'[JavaScript Error: "This login already exists." {file: "resource://gre/components/nsLoginManager.js" line: 308}]' when calling method: [nsILoginManager::addLogin])

As I deleted the ftp duplicates with format:
http://ftp.xxxx.yyy.zzz:port 

Now I am receiving error for all the entries with format ftp.xxxx.yyy.zzz:port 
https://ftp.mozilla.org:21 ([JavaScript Error: "Can't add a login without a httpRealm or formSubmitURL." {file: "resource://gre/components/nsLoginManager.js" line: 299}]'[JavaScript Error: "Can't add a login without a httpRealm or formSubmitURL." {file: "resource://gre/components/nsLoginManager.js" line: 299}]' when calling method: [nsILoginManager::addLogin])

I think maybe the addon should have the same verification controls for export and import, and not only during the import process.

**Comment by JustOff** [comment]
I guess your password database has a long history and some of the entries were created by rather old browser versions that had fewer restrictions than today. That is why some records are perceived as duplicate or erroneous when you try to restore them from backup. In such circumstances, Password Backup Tool does its best to save and restore data, and I do not see how this could be improved.

If you want to get a clean backup for future use, you can make it from a clean profile into which a "dirty" backup was imported. You can also save the original one in case you later need to manually enter data from records that could not be imported automatically.
