### ISSUE TITLE
Fail to merge passwords from palemoon 28 and ff 56

### ISSUE THREAD

**Issue by Janaue** [JustOff/password-backup-tool#5]
I have palemoon v28.7.0 portable and firefox 56b12 portable on w10. I want to merge all those passwords and have the same lists of passwords for both browsers. So I use PBT 1.2.1 on both and I export my passwords in.xml, but then when I import, in browser A, the list of browser B, I get an error in firefox (not possible to import the list), and nothing in palemoon.

When i import list of browser A, into browser A, it works, but ofc this is useless.

edit: Most of the passwords are already overlapping, so I do not want duplicates as well.

**Comment by JustOff** [comment]
Unfortunately, this tool is not intended to perform a merge. If you need to do this, export the data in csv format, use a text editor to merge and delete duplicates manually, and then import the result, after deleting all saved passwords from the target browser.

**Comment by Janaue** [comment]
I remember i used PBT to merge between palemoon and firefox a long time ago. and it even took care of the duplicates.

anyway, in the .xml for palemoon, the i see extxmlversion="2.0" and for firefox extxmlversion="1.1". can it be the problem?

**Comment by JustOff** [comment]
>  extxmlversion="1.1"

If you are trying to import backups created by Password Exporter, then this is not supported.

**Comment by Janaue** [comment]
I confused PBT with the clone program  Password Exporter 1.3.4  in your   Classic Add-ons Archive (2004-2018) 
this guy imports the firefox passwords into palemoon but not vice versa, so i will create the common list in palemoon and then just copy the key3.db and login file into firefox

**Comment by JustOff** [comment]
Well, in any case, I'd recommend using PBT in both Pale Moon and Firefox 56, as Password Exporter may incorrectly handle passwords with special characters and non-Latin letters.

**Comment by Janaue** [comment]
I made a clean profile of firefox 56 and palemoon 28 and now  Password Backup Tool Version 1.2.1
Updated on December 27, 2018  imports passwords from FF to PM and vice versa without any error.
