### ISSUE TITLE
Importing passwords from "Login Data" from Chrome shows that 0/0 of passwords have been imported

### ISSUE THREAD

**Issue by ACCELERATE1488** [JustOff/password-backup-tool#6]
What can I do to fix this?

**Comment by JustOff** [comment]
Please provide more details and ensure that you actually have saved passwords in the profile you importing from.

**Comment by ACCELERATE1488** [comment]
I do have passwords in the file, I have checked it, and even though its kind of unreadable, I can still find usernames and passwords in the file if I scroll down a bit

**Comment by ACCELERATE1488** [comment]
The file in question is 72 KBs

**Comment by JustOff** [comment]
Still need more details about OS, Chrome version, and which browser is used to run Password Backup Tool.

**Comment by ACCELERATE1488** [comment]
OS - Windows 10 64 bit
Chrome - 83.0.4103.116 64 bit
Browser used to run Backup Tool - PaleMoon 28.10.0 64 bit

**Comment by JustOff** [comment]
Is there are any errors in Browser Console (Ctrl+Shift+J) while importing?

**Comment by ACCELERATE1488** [comment]
`decryptData failed: 0`
Maybe chrome upgraded how it stores its passwords?

**Comment by JustOff** [comment]
Under Windows 7, everything is imported without problems, I will check Windows 10 as soon as I get to my second device.

**Comment by JustOff** [comment]
I was finally able to reproduce the issue. It seems to be necessary to update the Chrome import module according to [Bug#1613337](https://bugzilla.mozilla.org/show_bug.cgi?id=1613337).

**Comment by ACCELERATE1488** [comment]
Thanks

**Comment by JustOff** [comment]
Resolved in [PBT 1.3.0](https://github.com/JustOff/password-backup-tool/releases/tag/1.3.0).
